name: "JFrog CLI Example"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        with:
          version: 2.5.1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN_1 }}
