name: A workflow to publish to jfrog
on:
  workflow_dispatch:

jobs:
  build:
    name: publish to jfrog action
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.artifactory_token_1 }}
      - run: |
          # Ping the server
          jfrog rt ping
